import fs from 'fs';
import path from 'path';

import { Logger } from '../utils/Logger';

/**
 * SEO Module
 * Handles robots.txt, sitemap.xml, and spider configurations
 */
export class SEOModule {
  private config: Record<string, any>;
  private logger: Logger;
  private routes: Set<string>;
  private lastGenerated: number | null;

  constructor(config: Record<string, any>) {
    this.config = config;
    this.logger = new Logger(config.dev?.verbose);
    this.routes = new Set();
    this.lastGenerated = null;
  }

  async initialize() {
    this.logger.info('Initializing SEO Module...');
    
    // 注意：ISR/SSR模式下不生成静态文件，而是通过动态路由提供
    // 只有在SSG模式下才生成静态文件
    this.logger.info('SEO Module initialized (动态路由模式)');
    this.logger.info('访问 /robots.txt 和 /sitemap.xml 将通过动态路由提供');
  }

  async generateRobots() {
    try {
      const robotsPath = path.join(this.getOutputDir(), 'robots.txt');
      const robotsContent = this.createRobotsContent();

      await this.ensureDirectoryExists(path.dirname(robotsPath));
      await fs.promises.writeFile(robotsPath, robotsContent, 'utf-8');

      this.logger.info(`Robots.txt generated: ${robotsPath}`);
    } catch (error) {
      this.logger.error('Failed to generate robots.txt:', error);
      throw error;
    }
  }

  createRobotsContent() {
    const { baseUrl, domain, spiderConfig } = this.config;
    const siteUrl = baseUrl || domain || 'http://localhost:3000';
    const disallowPaths = this.getDisallowPaths();

    return `# Robots.txt generated by ISR Engine
# Generated at: ${new Date().toISOString()}

User-agent: *
${disallowPaths.map((path) => `Disallow: ${path}`).join('\n')}
Allow: /

# Crawl-delay for polite crawling
Crawl-delay: ${spiderConfig?.delay ? Math.floor(spiderConfig.delay / 1000) : 1}

# Sitemap location
Sitemap: ${siteUrl}/sitemap.xml

# Search engine specific rules
User-agent: Googlebot
Allow: /

User-agent: Bingbot
Allow: /

User-agent: Slurp
Allow: /

# Block problematic bots
User-agent: SemrushBot
Disallow: /

User-agent: AhrefsBot
Disallow: /

User-agent: MJ12bot
Disallow: /
`;
  }

  /**
   * 生成robots.txt内容（用于动态响应）
   */
  async generateRobotsContent(): Promise<string> {
    return this.createRobotsContent();
  }

  /**
   * 生成sitemap.xml内容（用于动态响应）
   */
  async generateSitemapContent(): Promise<string> {
    const routes = await this.getDiscoveredRoutes();
    return this.createSitemapContent(routes);
  }

  getDisallowPaths() {
    return [
      '/admin',
      '/api',
      '/private',
      '/_next',
      '/dist',
      '/node_modules',
      '/*.json',
      '/*.xml',
      '/.*', // Hidden files
    ];
  }

  async generateSitemap() {
    try {
      const sitemapPath = path.join(this.getOutputDir(), 'sitemap.xml');
      const routes = await this.getDiscoveredRoutes();

      const sitemapContent = this.createSitemapContent(routes);

      await this.ensureDirectoryExists(path.dirname(sitemapPath));
      await fs.promises.writeFile(sitemapPath, sitemapContent, 'utf-8');

      this.lastGenerated = Date.now();
      this.logger.info(
        `Sitemap generated with ${routes.length} URLs: ${sitemapPath}`
      );
    } catch (error) {
      this.logger.error('Failed to generate sitemap:', error);
      throw error;
    }
  }

  createSitemapContent(routes: string[]) {
    const { baseUrl, domain } = this.config;
    const siteUrl = baseUrl || domain || 'http://localhost:3000';

    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
${routes.map((route: string) => this.createSitemapEntry(route, siteUrl)).join('\n')}
</urlset>`;
  }

  createSitemapEntry(route: string, domain: string) {
    const url = route.startsWith('/') ? route : '/' + route;
    const fullUrl = domain + url;
    const priority = this.getRoutePriority(url);
    const changefreq = this.getRouteChangefreq(url);

    return `  <url>
    <loc>${fullUrl}</loc>
    <lastmod>${new Date().toISOString()}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
    <mobile:mobile/>
  </url>`;
  }

  getRoutePriority(route: string) {
    if (route === '/') return '1.0';
    if (route === '/about') return '0.8';
    if (route.startsWith('/blog/')) return '0.7';
    if (route.startsWith('/products/')) return '0.9';
    return '0.6';
  }

  getRouteChangefreq(route: string) {
    if (route === '/') return 'daily';
    if (route.startsWith('/blog/')) return 'weekly';
    if (route.startsWith('/products/')) return 'monthly';
    return 'monthly';
  }

  async getDiscoveredRoutes() {
    const routes = new Set(['/']); // Always include homepage

    // Add routes from configuration
    const configRoutes = await this.getConfigRoutes();
    configRoutes.forEach((route: string) => routes.add(route));

    // Add dynamically discovered routes
    this.routes.forEach((route) => routes.add(route));

    return Array.from(routes).sort();
  }

  async getConfigRoutes() {
    try {
      // Try to load routes from ssg.config.js or similar
      const configPaths = [
        path.join(process.cwd(), 'ssg.config.js'),
        path.join(process.cwd(), 'sitemap.config.js'),
      ];

      for (const configPath of configPaths) {
        if (await this.fileExists(configPath)) {
          const config = await import(configPath);
          return config.routes || config.default?.routes || [];
        }
      }
    } catch {
      this.logger.debug('No sitemap config found, using defaults');
    }

    return ['/about']; // Default routes
  }

  async runSpider() {
    if (!this.config.enableSpider) {
      this.logger.debug('Spider disabled');
      return;
    }

    this.logger.info('Running SEO spider...');

    try {
      const { SpiderEngine } = await import('./SpiderEngine');
      const spider = new SpiderEngine(this.config.spiderConfig);

      const results = await spider.crawl(this.config.domain);

      // Add discovered routes
      results.discoveredUrls.forEach((url) => {
        const route = new URL(url).pathname;
        this.addRoute(route);
      });

      this.logger.info(
        `Spider completed: ${results.discoveredUrls.length} URLs found`
      );

      // Regenerate sitemap with new routes
      if (results.discoveredUrls.length > 0) {
        await this.generateSitemap();
      }

      return results;
    } catch (error) {
      this.logger.error('Spider failed:', error);
      throw error;
    }
  }

  addRoute(route: string) {
    if (route && typeof route === 'string') {
      this.routes.add(route);
      this.logger.debug(`Route discovered: ${route}`);
    }
  }

  removeRoute(route: string) {
    this.routes.delete(route);
  }

  async regenerateAll() {
    this.logger.info('Regenerating all SEO assets...');

    await Promise.all([this.generateRobots(), this.generateSitemap()]);

    if (this.config.enableSpider) {
      await this.runSpider();
    }

    this.logger.info('SEO assets regenerated');
  }

  getOutputDir() {
    return this.config.outputDir || process.env.NODE_ENV === 'production'
      ? './dist/client'
      : './public';
  }

  async ensureDirectoryExists(dirPath: string) {
    try {
      await fs.promises.access(dirPath);
    } catch {
      await fs.promises.mkdir(dirPath, { recursive: true });
    }
  }

  async fileExists(filePath: string) {
    try {
      await fs.promises.access(filePath);
      return true;
    } catch {
      return false;
    }
  }

  getStats() {
    return {
      discoveredRoutes: this.routes.size,
      lastGenerated: this.lastGenerated,
      robotsEnabled: this.config.generateRobots,
      sitemapEnabled: this.config.generateSitemap,
      spiderEnabled: this.config.enableSpider,
    };
  }
}
