#!/usr/bin/env node
/**
 * fix-rsc-dts —— vite-plugin-dts 多 entry 时 sub-bundle 的 d.ts rollup 失败兜底。
 * dist/rsc/index.d.ts 默认输出 `export * from '../src/rsc/index'` 引用不发包路径。
 * 主 dist/novel-isr.d.ts 是正确 rolled up 的，含所有 RSC 符号。
 * 这里重写 dist/rsc/index.d.ts 从主 entry re-export。
 */
import { writeFileSync } from 'node:fs';

const RSC_VALUE_EXPORTS = [
  'revalidatePath',
  'revalidateTag',
  'registerInvalidator',
  'RevalidationError',
  'cacheTag',
  'collectTags',
  'runWithTagStore',
  'debugTagStore',
  'markUncacheable',
  'isUncacheable',
  'serverActionsRegistry',
  'createServerAction',
  'ServerActionUtils',
  'SERVER_ACTION_ENDPOINT',
  'LEGACY_SERVER_ACTION_ENDPOINT',
  'getVariant',
];
const RSC_TYPE_EXPORTS = ['RevalidateInvalidator', 'ServerActionMetadata', 'ServerActionHandler'];

const lines = [
  `// AUTO-GENERATED by scripts/fix-rsc-dts.mjs after vite build.`,
  `// vite-plugin-dts 多 entry 时 sub-bundle d.ts rollup 失败的兜底。`,
  ``,
  `export {`,
  ...RSC_VALUE_EXPORTS.map(n => `  ${n},`),
  `} from '../novel-isr';`,
  ``,
  `export type {`,
  ...RSC_TYPE_EXPORTS.map(n => `  ${n},`),
  `} from '../novel-isr';`,
  ``,
];
writeFileSync('dist/rsc/index.d.ts', lines.join('\n'));
console.log('✓ rewrote dist/rsc/index.d.ts');
